insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hamid Govey', 'Namekagon', '1989-04-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Thurston Eby', 'Twin Pines', '1975-03-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Randene Gonsalvez', 'Crowley', '1984-05-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Isacco Bogey', 'Monica', '1979-02-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Felipe Ivanikov', 'Jenna', '1986-07-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Latrena Hadwen', 'Delaware', '1981-05-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Giacomo Bottoms', 'Forster', '1975-08-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Eda Mattioni', 'Holy Cross', '1980-06-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marcelline Jenk', 'Aberg', '1984-04-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Robby Bazley', 'Hovde', '1987-08-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Adella Whatmough', 'Independence', '1978-04-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Skippy Guerreau', 'Harper', '1979-12-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lars Enticknap', 'Maywood', '1985-05-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gratiana Cheyney', 'Grasskamp', '1978-02-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hurlee Beedell', 'Moose', '1978-02-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Derick Sandhill', 'Pearson', '1984-08-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Glenda Forrest', 'Mifflin', '1977-10-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Suki Andrasch', 'Bay', '1985-01-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Teddi Abramowsky', 'Straubel', '1989-09-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hope Edens', 'Claremont', '1973-08-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Augustine Jacob', 'Pearson', '1980-07-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Elwin Bozward', 'Blackbird', '1987-02-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Phillie Addess', 'International', '1982-11-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tabina Lunck', 'Talmadge', '1983-12-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Melonie Wrettum', 'East', '1981-12-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sidoney Paulou', 'Linden', '1981-05-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sande Vedeniktov', 'Debra', '1986-11-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Janela Obeney', 'Southridge', '1986-04-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Daffi Gounot', 'Cascade', '1986-02-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ardelle Hodgets', 'Burrows', '1978-04-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Celestyna MacAlroy', 'Canary', '1973-11-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kip Glyde', 'Browning', '1987-12-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('L;urette Isakov', 'La Follette', '1981-04-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gage Santhouse', 'Susan', '1987-10-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nester Fabbri', 'Starling', '1980-03-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gaylor Campagne', '1st', '1983-06-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rollo Saban', 'Harper', '1978-11-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Corrine Brocklesby', 'Oak', '1976-03-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Patin Stienton', 'Roth', '1983-02-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lukas Mousley', 'Barnett', '1988-12-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gualterio Gascone', 'Ryan', '1976-03-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Chery Naris', 'Birchwood', '1981-11-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ariela Calleja', 'Eastlawn', '1988-02-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jordan Sabati', 'Tennessee', '1983-04-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lynn Elgram', 'Shopko', '1979-12-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nikki Serjeantson', 'Farwell', '1985-07-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rosina Pawlyn', 'Algoma', '1975-01-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sally Guitt', 'Killdeer', '1972-12-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ben Nazareth', 'Vahlen', '1986-03-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lyon Murray', 'Muir', '1973-11-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Brenna Tomlinson', 'Sherman', '1981-03-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Celle Shynn', 'Linden', '1980-12-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ursa Reeme', 'Northview', '1987-12-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dani Crichten', 'Mccormick', '1973-04-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Elfrida Lowis', 'Spaight', '1981-09-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pepita Barth', 'Northridge', '1975-09-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Idelle McGhie', 'Valley Edge', '1985-05-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mufinella Kiff', 'Cardinal', '1975-11-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Winifred McHugh', 'Algoma', '1985-11-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gan Krelle', 'Dorton', '1989-04-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pat Smithyman', 'Darwin', '1973-07-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Alyson Instock', 'West', '1984-09-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maryrose Cheverton', 'Bartillon', '1980-01-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kevan Ert', 'Village Green', '1985-02-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ryon Truin', 'Starling', '1982-01-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nert Cazalet', 'Coleman', '1989-07-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Isidro McKeachie', 'Doe Crossing', '1982-09-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hale Lovart', 'Towne', '1982-05-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tess O'' Byrne', 'Stoughton', '1988-09-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kasey Minucci', 'Anzinger', '1979-04-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hakeem Sumnall', 'Annamark', '1978-10-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tad Ceney', 'Northridge', '1985-01-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Leoine Plaschke', 'Melby', '1974-12-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gianni Munslow', 'Elmside', '1989-01-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kipp Kealy', 'Welch', '1972-11-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mickie Ghidetti', 'Service', '1985-10-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bobine Exell', 'Jay', '1989-03-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Verina Matteoli', 'American Ash', '1980-03-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Andriette Magovern', 'Forest Run', '1982-12-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Frederic Riep', 'Coolidge', '1975-07-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Terrence Linne', 'Grasskamp', '1985-11-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nikolos Filisov', 'Fallview', '1982-07-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Darcee Whiteson', 'High Crossing', '1976-09-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Vincenz Smalecombe', 'Elgar', '1977-09-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ruperta Haffner', 'Granby', '1987-02-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Darya Cranny', 'Spaight', '1978-12-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Leighton Folley', 'Schiller', '1989-06-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Izak Langforth', 'Charing Cross', '1982-11-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Karlotta McDuff', 'Northfield', '1977-12-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jeremiah Knibley', 'Forest Dale', '1980-01-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Delora Farrants', 'Laurel', '1974-09-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cointon Thorley', 'Emmet', '1980-11-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hersh Jeyes', 'Lighthouse Bay', '1989-02-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nap Jacqueminot', 'Gateway', '1988-04-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Keen Woods', 'Summer Ridge', '1988-10-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Leonie Jelks', 'Cottonwood', '1979-01-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Verine Harradence', 'Twin Pines', '1984-02-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kaine Beauchop', '6th', '1983-09-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bord Merrydew', 'Cambridge', '1985-07-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ulrica McAloren', 'Little Fleur', '1976-07-16');