insert into tren (modelo, capacidad) values ('Xterra', 1);
insert into tren (modelo, capacidad) values ('XJ Series', 2);
insert into tren (modelo, capacidad) values ('Avalon', 3);
insert into tren (modelo, capacidad) values ('CL-Class', 4);
insert into tren (modelo, capacidad) values ('Cabriolet', 5);
insert into tren (modelo, capacidad) values ('Horizon', 6);
insert into tren (modelo, capacidad) values ('CX-7', 7);
insert into tren (modelo, capacidad) values ('Corvette', 8);
insert into tren (modelo, capacidad) values ('Escape', 9);
insert into tren (modelo, capacidad) values ('Commander', 10);
insert into tren (modelo, capacidad) values ('Sienna', 11);
insert into tren (modelo, capacidad) values ('RX-8', 12);
insert into tren (modelo, capacidad) values ('2500', 13);
insert into tren (modelo, capacidad) values ('Topaz', 14);
insert into tren (modelo, capacidad) values ('Cougar', 15);
insert into tren (modelo, capacidad) values ('Sterling', 16);
insert into tren (modelo, capacidad) values ('Charger', 17);
insert into tren (modelo, capacidad) values ('Mustang', 18);
insert into tren (modelo, capacidad) values ('Suburban 2500', 19);
insert into tren (modelo, capacidad) values ('6 Series', 20);
insert into tren (modelo, capacidad) values ('E350', 21);
insert into tren (modelo, capacidad) values ('Ram 1500', 22);
insert into tren (modelo, capacidad) values ('Nuova 500', 23);
insert into tren (modelo, capacidad) values ('Fiesta', 24);
insert into tren (modelo, capacidad) values ('Genesis Coupe', 25);
insert into tren (modelo, capacidad) values ('Vandura 3500', 26);
insert into tren (modelo, capacidad) values ('C/V', 27);
insert into tren (modelo, capacidad) values ('Passat', 28);
insert into tren (modelo, capacidad) values ('Express 3500', 29);
insert into tren (modelo, capacidad) values ('Murciélago', 30);
insert into tren (modelo, capacidad) values ('S-Class', 31);
insert into tren (modelo, capacidad) values ('Enclave', 32);
insert into tren (modelo, capacidad) values ('Town Car', 33);
insert into tren (modelo, capacidad) values ('W201', 34);
insert into tren (modelo, capacidad) values ('Corvette', 35);
insert into tren (modelo, capacidad) values ('Navigator', 36);
insert into tren (modelo, capacidad) values ('Galant', 37);
insert into tren (modelo, capacidad) values ('Roadmaster', 38);
insert into tren (modelo, capacidad) values ('Element', 39);
insert into tren (modelo, capacidad) values ('Sportvan G30', 40);
insert into tren (modelo, capacidad) values ('A4', 41);
insert into tren (modelo, capacidad) values ('Maxima', 42);
insert into tren (modelo, capacidad) values ('9-5', 43);
insert into tren (modelo, capacidad) values ('G', 44);
insert into tren (modelo, capacidad) values ('IS F', 45);
insert into tren (modelo, capacidad) values ('S40', 46);
insert into tren (modelo, capacidad) values ('G-Class', 47);
insert into tren (modelo, capacidad) values ('Land Cruiser', 48);
insert into tren (modelo, capacidad) values ('V50', 49);
insert into tren (modelo, capacidad) values ('Firebird', 50);
insert into tren (modelo, capacidad) values ('Cabriolet', 51);
insert into tren (modelo, capacidad) values ('MX-5', 52);
insert into tren (modelo, capacidad) values ('CC', 53);
insert into tren (modelo, capacidad) values ('Yukon XL 2500', 54);
insert into tren (modelo, capacidad) values ('RL', 55);
insert into tren (modelo, capacidad) values ('550', 56);
insert into tren (modelo, capacidad) values ('Corvair', 57);
insert into tren (modelo, capacidad) values ('Alpina B7', 58);
insert into tren (modelo, capacidad) values ('Charger', 59);
insert into tren (modelo, capacidad) values ('X5 M', 60);
insert into tren (modelo, capacidad) values ('Sportvan G30', 61);
insert into tren (modelo, capacidad) values ('8 Series', 62);
insert into tren (modelo, capacidad) values ('Continental GTC', 63);
insert into tren (modelo, capacidad) values ('Aerio', 64);
insert into tren (modelo, capacidad) values ('Eclipse', 65);
insert into tren (modelo, capacidad) values ('E-Series', 66);
insert into tren (modelo, capacidad) values ('Corolla', 67);
insert into tren (modelo, capacidad) values ('911', 68);
insert into tren (modelo, capacidad) values ('E350', 69);
insert into tren (modelo, capacidad) values ('Golf', 70);
insert into tren (modelo, capacidad) values ('LS', 71);
insert into tren (modelo, capacidad) values ('Laser', 72);
insert into tren (modelo, capacidad) values ('TT', 73);
insert into tren (modelo, capacidad) values ('Tribeca', 74);
insert into tren (modelo, capacidad) values ('F-Series', 75);
insert into tren (modelo, capacidad) values ('Uplander', 76);
insert into tren (modelo, capacidad) values ('Optima', 77);
insert into tren (modelo, capacidad) values ('Electra', 78);
insert into tren (modelo, capacidad) values ('rio', 79);
insert into tren (modelo, capacidad) values ('Express 1500', 80);
insert into tren (modelo, capacidad) values ('Rally Wagon 3500', 81);
insert into tren (modelo, capacidad) values ('CLK-Class', 82);
insert into tren (modelo, capacidad) values ('H2', 83);
insert into tren (modelo, capacidad) values ('Altima', 84);
insert into tren (modelo, capacidad) values ('Vibe', 85);
insert into tren (modelo, capacidad) values ('E250', 86);
insert into tren (modelo, capacidad) values ('G-Series 1500', 87);
insert into tren (modelo, capacidad) values ('E-Series', 88);
insert into tren (modelo, capacidad) values ('Tempo', 89);
insert into tren (modelo, capacidad) values ('Tiburon', 90);
insert into tren (modelo, capacidad) values ('300ZX', 91);
insert into tren (modelo, capacidad) values ('Ram 2500', 92);
insert into tren (modelo, capacidad) values ('Safari', 93);
insert into tren (modelo, capacidad) values ('Safari', 94);
insert into tren (modelo, capacidad) values ('Mighty Max Macro', 95);
insert into tren (modelo, capacidad) values ('NSX', 96);
insert into tren (modelo, capacidad) values ('XG350', 97);
insert into tren (modelo, capacidad) values ('Corsica', 98);
insert into tren (modelo, capacidad) values ('E-Class', 99);
insert into tren (modelo, capacidad) values ('G5', 100);